"""add master theses tables

Revision ID: 017a198cc0f3
Revises: 0a2e99e5aaae
Create Date: 2026-05-12 12:10:14.622138

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '017a198cc0f3'
down_revision: Union[str, Sequence[str], None] = '0a2e99e5aaae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_theses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thesis_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('keywords', sa.Text(), nullable=True),
    sa.Column('related_activity_optional', sa.String(), nullable=True),
    sa.Column('related_project_optional', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('prerequisites', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('student_name_optional', sa.String(length=200), nullable=True),
    sa.Column('created_by_person_id', sa.String(), nullable=True),
    sa.Column('assigned_at_optional', sa.String(length=50), nullable=True),
    sa.Column('completed_at_optional', sa.String(length=50), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['related_activity_optional'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['related_project_optional'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('thesis_code')
    )
    op.create_table('thesis_supervisors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thesis_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['thesis_id'], ['master_theses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('thesis_supervisors')
    op.drop_table('master_theses')
    # ### end Alembic commands ###
