"""add meetings tables

Revision ID: 0a2e99e5aaae
Revises: 8901bc2c44e5
Create Date: 2026-05-12 11:56:10.508131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a2e99e5aaae'
down_revision: Union[str, Sequence[str], None] = '8901bc2c44e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meeting_purposes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meeting_types',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('meetings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('meeting_type_id', sa.String(), nullable=False),
    sa.Column('organizer_person_id', sa.String(), nullable=False),
    sa.Column('meeting_date', sa.String(length=50), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time_optional', sa.String(length=50), nullable=True),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_type_id'], ['meeting_types.id'], ),
    sa.ForeignKeyConstraint(['organizer_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_slots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(length=50), nullable=False),
    sa.Column('end_time', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('taken_by_person_id_optional', sa.String(), nullable=True),
    sa.Column('activity_id_optional', sa.String(), nullable=True),
    sa.Column('purpose_id_optional', sa.String(), nullable=True),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('confirmed_presented', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id_optional'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ),
    sa.ForeignKeyConstraint(['purpose_id_optional'], ['meeting_purposes.id'], ),
    sa.ForeignKeyConstraint(['taken_by_person_id_optional'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_slot_presenters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_slot_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_slot_id'], ['meeting_slots.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('meeting_slot_presenters')
    op.drop_table('meeting_slots')
    op.drop_table('meetings')
    op.drop_table('meeting_types')
    op.drop_table('meeting_purposes')
    # ### end Alembic commands ###
