"""add activities and publications tables

Revision ID: 17d8182838b4
Revises: aa30ec6ad957
Create Date: 2026-05-12 11:32:36.898109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17d8182838b4'
down_revision: Union[str, Sequence[str], None] = 'aa30ec6ad957'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_stages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publication_statuses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('workflow_group', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('research_fields',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('activities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('field_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('current_stage_id', sa.String(), nullable=False),
    sa.Column('main_assignee_person_id', sa.String(), nullable=False),
    sa.Column('supervisor_person_id', sa.String(), nullable=False),
    sa.Column('last_presented_at_optional', sa.String(length=50), nullable=True),
    sa.Column('created_by_person_id', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['current_stage_id'], ['activity_stages.id'], ),
    sa.ForeignKeyConstraint(['field_id'], ['research_fields.id'], ),
    sa.ForeignKeyConstraint(['main_assignee_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['supervisor_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('activity_code')
    )
    op.create_table('publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publication_code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('current_status_id', sa.String(), nullable=False),
    sa.Column('main_author_person_id', sa.String(), nullable=False),
    sa.Column('supervisor_person_id', sa.String(), nullable=False),
    sa.Column('journal_name_optional', sa.String(length=300), nullable=True),
    sa.Column('conference_name_optional', sa.String(length=300), nullable=True),
    sa.Column('conference_date_optional', sa.String(length=50), nullable=True),
    sa.Column('conference_place_optional', sa.String(length=300), nullable=True),
    sa.Column('description_optional', sa.Text(), nullable=True),
    sa.Column('created_by_person_id', sa.String(), nullable=True),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['current_status_id'], ['publication_statuses.id'], ),
    sa.ForeignKeyConstraint(['main_author_person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['supervisor_person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('publication_code')
    )
    op.create_table('activity_collaborators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_deadlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('activity_stage_id', sa.String(), nullable=False),
    sa.Column('deadline_optional', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['activity_stage_id'], ['activity_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_publications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('activity_id', sa.String(), nullable=False),
    sa.Column('publication_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_collaborators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publication_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication_deadlines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('publication_id', sa.String(), nullable=False),
    sa.Column('publication_status_id', sa.String(), nullable=False),
    sa.Column('deadline_optional', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['publication_id'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['publication_status_id'], ['publication_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publication_deadlines')
    op.drop_table('publication_collaborators')
    op.drop_table('activity_publications')
    op.drop_table('activity_projects')
    op.drop_table('activity_deadlines')
    op.drop_table('activity_collaborators')
    op.drop_table('publications')
    op.drop_table('activities')
    op.drop_table('research_fields')
    op.drop_table('publication_statuses')
    op.drop_table('activity_stages')
    # ### end Alembic commands ###
