"""add master theses tables

Revision ID: 696803decf77
Revises: b7f8546a7a3a
Create Date: 2026-05-12 12:39:46.127835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '696803decf77'
down_revision: Union[str, Sequence[str], None] = 'b7f8546a7a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'roles',
        sa.Column('archived', sa.Boolean(), nullable=False, server_default=sa.false())
    )    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'archived')
    # ### end Alembic commands ###
