"""add activities and publications tables

Revision ID: 8901bc2c44e5
Revises: 57a3a1dd2787
Create Date: 2026-05-12 11:51:23.137594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8901bc2c44e5'
down_revision: Union[str, Sequence[str], None] = '57a3a1dd2787'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
